version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: simulacred
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"